deathlog_strings_it = {
	main_font = "Fonts\\FRIZQT__.TTF",
	class_font = "Fonts\\blei00d.TTF",
	death_alert_font = "Fonts\\blei00d.TTF",
	mini_log_font = "Fonts\\blei00d.TTF",
	menu_font = "Fonts\\blei00d.TTF",
	deadliest_creature_container_font = "Fonts\\blei00d.TTF",
	death_alert_default_message = "<name> the <race> <class> has been slain\nby <source> at lvl <level> in <zone>.",
	death_alert_default_fall_message = "<name> the <race> <class> fell to\ndeath at lvl <level> in <zone>.",
	death_alert_default_drown_message = "<name> the <race> <class> drowned\n at lvl <level> in <zone>.",
	death_alert_default_slime_message = "<name> the <race> <class> has died from slime.\n at lvl <level> in <zone>.",
	death_alert_default_lava_message = "<name> the <race> <class> drowned in lava.\n at lvl <level> in <zone>.",
	death_alert_default_fire_message = "<name> the <race> <class> has died from fire.\n at lvl <level> in <zone>.",
	death_alert_default_fatigue_message = "<name> the <race> <class> has died from fatigue.\n at lvl <level> in <zone>.",
	corpse_word = "Cadavere",
	of_word = "Di",
	minimap_btn_left_click = "|cFF666666Left Click:|r View log",
	minimap_btn_right_click = "|cFF666666Right Click:|r ",
	class_word = "Class",
	killed_by_word = "Killed by",
	zone_instance_word = "Zone/Instance",
	date_word = "Date",
	last_words_word = "Last words",
	death_word = "Death",
	guild_word = "Guild",
	race_word = "Race",
	show_heatmap = "Show heatmap",
	class_table = {
		Warrior = "warrior",
		Rogue = "rogue",
		Mage = "mage",
		Priest = "priest",
		Paladin = "paladin",
		Shaman = "shaman",
		Druid = "druid",
		Warlock = "warlock",
		Hunter = "hunter",
	},
	tab_table = {
		{ value = "ClassStatisticsTab", text = "Class Statistics" },
		{ value = "CreatureStatisticsTab", text = "Creature Statistics" },
		{ value = "InstanceStatisticsTab", text = "Instance Statistics" },
		{ value = "StatisticsTab", text = "Zone Statistics" },
		{ value = "LogTab", text = "Search" },
	},
	instance_tbl = {
		{ 33, "SHADOWFANGKEEP", "Shadowfang Keep" },
		{ 36, "DEADMINES", "Deadmines" },
		{ 34, "STORMWINDSTOCKADES", "Stockades" },
		{ 43, "WAILINGCAVERNS", "Wailing Caverns" },
		{ 47, "RAZORFENKRAUL", "Razorfen Kraul" },
		{ 48, "BLACKFATHOMDEEPS", "Blackfathom Deeps" },
		{ 90, "GNOMEREGAN", "Gnomeregan" },
		{ 189, "SCARLETMONASTERY", "Scarlet Monastery" },
		{ 70, "ULDAMAN", "Uldaman" },
		{ 109, "SUNKENTEMPLE", "Sunken Temple" },
		{ 129, "RAZORFENDOWNS", "Razorfen Downs" },
		{ 209, "ZULFARAK", "Zul'Farak" },
		{ 229, "BLACKROCKSPIRE", "Blackrock Spire" },
		{ 230, "BLACKROCKDEPTHS", "Blackrock Depths" },
		{ 289, "SCHOLOMANCE", "Scholomance" },
		{ 329, "STRATHOLME", "Stratholme" },
		{ 349, "MARAUDON", "Maraudon" },
		{ 389, "RAGEFIRECHASM", "Ragefire Chasm" },
		{ 429, "DIREMAUL", "Diremaul" },
		{ 469, "BLACKWINGLAIR", "Blackwing Lair" },
	},
	instance_map = {
		["Shadowfang Keep"] = 33,
		["Stormwind Stockade"] = 34,
		["Deadmines"] = 36,
		["Wailing Caverns"] = 43,
		["Razorfen Kraul"] = 47,
		["Blackfathom Deeps"] = 48,
		["Uldaman"] = 70,
		["Gnomeregan"] = 90,
		["Sunken Temple"] = 109,
		["Razorfen Downs"] = 129,
		["Scarlet Monastery"] = 189,
		["Zul'Farrak"] = 209,
		["Blackrock Spire"] = 229,
		["Blackrock Depths"] = 230,
		["Scholomance"] = 289,
		["Stratholme"] = 329,
		["Maraudon"] = 349,
		["Ragefire Chasm"] = 389,
		["Dire Maul"] = 429,
		["Blackwing Lair"] = 469,
	},
	deathlog_zone_tbl = {
		["Azeroth"] = 947,
		["Durotar"] = 1411,
		["Mulgore"] = 1412,
		["The Barrens"] = 1413,
		["Kalimdor"] = 1414,
		["Eastern Kingdoms"] = 1415,
		["Alterac Mountains"] = 1416,
		["Arathi Highlands"] = 1417,
		["Badlands"] = 1418,
		["Blasted Lands"] = 1419,
		["Tirisfal Glades"] = 1420,
		["Silverpine Forest"] = 1421,
		["Western Plaguelands"] = 1422,
		["Eastern Plaguelands"] = 1423,
		["Hillsbrad Foothills"] = 1424,
		["The Hinterlands"] = 1425,
		["Dun Morogh"] = 1426,
		["Searing Gorge"] = 1427,
		["Burning Steppes"] = 1428,
		["Elwynn Forest"] = 1429,
		["Deadwind Pass"] = 1430,
		["Duskwood"] = 1431,
		["Loch Modan"] = 1432,
		["Redridge Mountains"] = 1433,
		["Stranglethorn Vale"] = 1434,
		["Swamp of Sorrows"] = 1435,
		["Westfall"] = 1436,
		["Wetlands"] = 1437,
		["Teldrassil"] = 1438,
		["Darkshore"] = 1439,
		["Ashenvale"] = 1440,
		["Thousand Needles"] = 1441,
		["Stonetalon Mountains"] = 1442,
		["Desolace"] = 1443,
		["Feralas"] = 1444,
		["Dustwallow Marsh"] = 1445,
		["Tanaris"] = 1446,
		["Azshara"] = 1447,
		["Felwood"] = 1448,
		["Un'Goro Crater"] = 1449,
		["Moonglade"] = 1450,
		["Silithus"] = 1451,
		["Winterspring"] = 1452,
	},
}
