deathlog_strings_ru = {
	-- fonts
	main_font = "Fonts\\NIM_____.ttf",
	class_font = "Fonts\\NIM_____.ttf",
	death_alert_font = "Fonts\\NIM_____.ttf",
	mini_log_font = "Fonts\\MORPHEUS_CYR.TTF",
	menu_font = "Fonts\\NIM_____.ttf",
	deadliest_creature_container_font = "Fonts\\FRIZQT___CYR.TTF",
	creature_model_quote_font = "Fonts\\MORPHEUS_CYR.TTF",
	-- death alerts messages
	death_alert_default_message = "<name> <race> <class> был убит\n<source> на уровне <level> в <zone>.",
	death_alert_default_fall_message = "<name> <race> <class> разбился\nнасмерть на уровне <level> в <zone>.",
	death_alert_default_drown_message = "<name> <race> <class> утонул\n на уровне <level> в <zone>.",
	death_alert_default_slime_message = "<name> <race> <class> умер от слизи.\n на уровне <level> в <zone>.",
	death_alert_default_lava_message = "<name> <race> <class> утонул в лаве.\n на уровне <level> в <zone>.",
	death_alert_default_fire_message = "<name> <race> <class> умер от огня.\n на уровне <level> в <zone>.",
	death_alert_default_fatigue_message = "<name> <race> <class> умер от усталости.\n на уровне <level> в <zone>.",
	-- words
	corpse_word = "Труп",
	of_word = "из",
	minimap_btn_left_click = "|cFF666666ЛКМ:|r Посмотреть журнал",
 	minimap_btn_right_click = "|cFF666666ПКМ:|r ",
	class_word = "Класс",
	killed_by_word = "Убит",
	zone_instance_word = "Зона/Подземелье",
	date_word = "Дата",
	last_words_word = "Последние слова",
	death_word = "Смерть",
	guild_word = "Гильдия",
	race_word = "Раса",
	name_word = "Имя",
	show_heatmap = "Heatmap",
	-- tables
	class_table = {
		Warrior = "воин",
		Rogue = "разбойник",
		Mage = "маг",
		Priest = "жрец",
		Paladin = "паладин",
		Shaman = "шаман",
		Druid = "друид",
		Warlock = "чернокнижник",
		Hunter = "охотник",
	},
	tab_table = {
		{ value = "ClassStatisticsTab", text = "Статистика классов" },
		{ value = "CreatureStatisticsTab", text = "Статистика существ" },
		{ value = "InstanceStatisticsTab", text = "Статистика подземелий" },
		{ value = "StatisticsTab", text = "Статистика зон" },
		{ value = "LogTab", text = "Поиск" },
	},
	instance_tbl = {
		{ 33, "SHADOWFANGKEEP", "Крепость Темного Клыка" },
		{ 36, "DEADMINES", "Мертвые копи" },
		{ 34, "STORMWINDSTOCKADES", "Тюрьма" },
		{ 43, "WAILINGCAVERNS", "Пещеры Стенаний" },
		{ 47, "RAZORFENKRAUL", "Лабиринты Иглошкурых" },
		{ 48, "BLACKFATHOMDEEPS", "Непроглядная Пучина" },
		{ 90, "GNOMEREGAN", "Гномреган" },
		{ 189, "SCARLETMONASTERY", "Монастырь Алого ордена" },
		{ 70, "ULDAMAN", "Ульдаман" },
		{ 109, "SUNKENTEMPLE", "Храм Атал'Хаккара" },
		{ 129, "RAZORFENDOWNS", "Курганы Иглошкурых" },
		{ 209, "ZULFARAK", "Зул'Фаррак" },
		{ 229, "BLACKROCKSPIRE", "Вершина Черной горы" },
		{ 230, "BLACKROCKDEPTHS", "Глубины Черной горы" },
		{ 289, "SCHOLOMANCE", "Некроситет" },
		{ 329, "STRATHOLME", "Стратхольм" },
		{ 349, "MARAUDON", "Мародон" },
		{ 389, "RAGEFIRECHASM", "Огненная пропасть" },
		{ 429, "DIREMAUL", "Забытый Город" },
		{ 469, "BLACKWINGLAIR", "Логово Крыла Тьмы" },
	},
	instance_map = {
		["Крепость Темного Клыка"] = 33,
		["Тюрьма"] = 34,
		["Мертвые копи"] = 36,
		["Пещеры Стенаний"] = 43,
		["Лабиринты Иглошкурых"] = 47,
		["Непроглядная Пучина"] = 48,
		["Ульдаман"] = 70,
		["Гномреган"] = 90,
		["Храм Атал'Хаккара"] = 109,
		["Курганы Иглошкурых"] = 129,
		["Монастырь Алого ордена"] = 189,
		["Зул'Фаррак"] = 209,
		["Вершина Черной горы"] = 229,
		["Глубины Черной горы"] = 230,
		["Некроситет"] = 289,
		["Стратхольм"] = 329,
		["Мародон"] = 349,
		["Огненная пропасть"] = 389,
		["Забытый Город"] = 429,
		["Логово Крыла Тьмы"] = 469,
	},
	deathlog_zone_tbl = {
		["Азерот"] = 947,
		["Дуротар"] = 1411,
		["Мулгор"] = 1412,
		["Степи"] = 1413,
		["Калимдор"] = 1414,
		["Восточные королевства"] = 1415,
		["Альтеракские горы"] = 1416,
		["Нагорье Арати"] = 1417,
		["Бесплодные земли"] = 1418,
		["Выжженные земли"] = 1419,
		["Тирисфальские леса"] = 1420,
		["Серебряный бор"] = 1421,
		["Западные Чумные земли"] = 1422,
		["Восточные Чумные земли"] = 1423,
		["Предгорья Хилсбрада"] = 1424,
		["Внутренние земли"] = 1425,
		["Дун Морог"] = 1426,
		["Тлеющее ущелье"] = 1427,
		["Пылающие степи"] = 1428,
		["Элвиннский лес"] = 1429,
		["Перевал Мертвого Ветра"] = 1430,
		["Сумеречный лес"] = 1431,
		["Лок Модан"] = 1432,
		["Красногорье"] = 1433,
		["Тернистая долина"] = 1434,
		["Болото Печали"] = 1435,
		["Западный Край"] = 1436,
		["Болотина"] = 1437,
		["Тельдрассил"] = 1438,
		["Темные берега"] = 1439,
		["Ясеневый лес"] = 1440,
		["Тысяча Игл"] = 1441,
		["Когтистые горы"] = 1442,
		["Пустоши"] = 1443,
		["Фералас"] = 1444,
		["Пылевые топи"] = 1445,
		["Танарис"] = 1446,
		["Азшара"] = 1447,
		["Оскверненный лес"] = 1448,
		["Кратер Ун'Горо"] = 1449,
		["Лунная поляна"] = 1450,
		["Силитус"] = 1451,
		["Зимние Ключи"] = 1452,
	},
	id_to_quote = {
		[6] = "Yiieeeee! Me run!",
		[38] = "I see those fools at the Abbey sent some fresh meat for us.",
		[40] = "You no take candle!",
		[80] = "Yiieeeee! Me run!",
		[95] = "Ah, a chance to use this freshly sharpened blade.",
		[97] = "Grrrr... fresh meat!",
		[98] = "More bones to gnaw on...",
		[117] = "Grrrr... fresh meat!",
		[121] = "Ah, a chance to use this freshly sharpened blade.",
		[122] = "Ah, a chance to use this freshly sharpened blade.",
		[123] = "Grrrr... fresh meat!",
		[124] = "Grrrr... fresh meat!",
		[212] = "I'll crush you!",
		[257] = "Yiieeeee! Me run!",
		[314] = "Aber?  Is that you...?  Oh...I'm so hungry, Aber!  SO HUNGRY!!",
		[315] = "I shall spill your blood, &lt;class&gt;!",
		[327] = "You no take candle!",
		[412] = "ИНТЕРЕСНО... ОРКИ ВКУСНЫЕ?",
		[423] = "Grrrr... fresh meat!",
		[424] = "Grrrr... fresh meat!",
		[426] = "Grrrr... fresh meat!",
		[429] = "Grrrr... fresh meat!",
		[430] = "Grrrr... fresh meat!",
		[431] = "Grrrr... fresh meat!",
		[432] = "Grrrr... fresh meat!",
		[433] = "Grrrr... fresh meat!",
		[434] = "Grrrr... fresh meat!",
		[445] = "Grrrr... fresh meat!",
		[446] = "Grrrr... fresh meat!",
		[452] = "Grrrr... fresh meat!",
		[475] = "You no take candle!",
		[476] = "You no take candle!",
		[478] = "Grrrr... fresh meat!",
		[481] = "Ah, a chance to use this freshly sharpened blade.",
		[500] = "Grrrr... fresh meat!",
		[504] = "Ah, a chance to use this freshly sharpened blade.",
		[568] = "Grrrr... fresh meat!",
		[580] = "Grrrr... fresh meat!",
		[589] = "Feel the power of the Brotherhood!",
		[590] = "Ah, a chance to use this freshly sharpened blade.",
		[639] = "And stay down!",
		[644] = "VanCleef pay big for you heads!",
		[646] = "D'ah! Now you're making me angry!",
		[8891] = "You can't hide from us.  Prepare to burn!",
		[706] = "I gonna make you into mojo!",
		[709] = "Me smash! You die!",
		[712] = "Grrrr... fresh meat!",
		[946] = "Killing you be easy.",
		[1007] = "Grrrr... fresh meat!",
		[1008] = "Grrrr... fresh meat!",
		[1009] = "Grrrr... fresh meat!",
		[1010] = "Grrrr... fresh meat!",
		[1011] = "Grrrr... fresh meat!",
		[1012] = "Grrrr... fresh meat!",
		[1051] = "Feel the power of the Dark Iron Dwarves!",
		[1052] = "Feel the power of the Dark Iron Dwarves!",
		[1053] = "Feel the power of the Dark Iron Dwarves!",
		[1115] = "Crush!",
		[1117] = "Crush!",
		[1121] = "I gonna make you into mojo!",
		[1123] = "I gonna make you into mojo!",
		[1157] = "A living human... soon to be a dead like me.",
		[1158] = "A living human... soon to be a dead like me.",
		[1161] = "Crush!",
		[1162] = "Crush!",
		[1163] = "Crush!",
		[1164] = "Crush!",
		[1165] = "Crush!",
		[1166] = "Crush!",
		[1167] = "Crush!",
		[1172] = "Me no run from &lt;class&gt; like you!",
		[1173] = "Me no run from &lt;class&gt; like you!",
		[1174] = "Me no run from &lt;class&gt; like you!",
		[1175] = "Me no run from &lt;class&gt; like you!",
		[1176] = "Me no run from &lt;class&gt; like you!",
		[1179] = "I'll crush you!",
		[1180] = "Me smash! You die!",
		[1197] = "Crush!",
		[1202] = "Me no run from &lt;class&gt; like you!",
		[1211] = "I'll cut you!",
		[1222] = "Wahehe! I'm taking you down with me!",
		[1236] = "You no take candle!",
		[9545] = "",
		[9547] = "",
		[1657] = "Here to visit the family?  Die, fool!",
		[1674] = "Grrrr... fresh meat!",
		[1675] = "Grrrr... fresh meat!",
		[1716] = "Tell the Warden this prison is ours now!",
		[1755] = "The Defias shall succeed! No meek adventurer will stop us!",
		[1756] = "A living legend...",
		[1770] = "The Sons of Arugal will rise against all who challenge the power of the Moonrage!",
		[1939] = "Grrrr... fresh meat!",
		[1940] = "Grrrr... fresh meat!",
		[1941] = "Grrrr... fresh meat!",
		[1942] = "Grrrr... fresh meat!",
		[10184] = "How fortuitous. Usually, I must leave my lair in order to feed.",
		[10373] = "What the... nobody cleanses a furbolg in MY camp!  Face the wrath of Xabraxxis!",
		[10440] = "I shall take great pleasure in taking this poor wretch's life!  It's not too late, she needn't suffer in vain.  Turn back and her death shall be merciful!",
		[2252] = "I'll crush you!",
		[2253] = "I'll crush you!",
		[2254] = "I'll crush you!",
		[2287] = "I'll crush you!",
		[2338] = "Carnage!  May I spill blood in His name!",
		[2339] = "Carnage!  May I spill blood in His name!",
		[2529] = "Орк, ты следующий!",
		[2564] = "I'll crush you!",
		[2566] = "I'll crush you!",
		[2567] = "I'll crush you!",
		[2691] = "Attack, my sisters! The troll must not escape!",
		[2716] = "I'll crush you!",
		[2717] = "I'll crush you!",
		[2748] = "Awake, ye servants! Defend the Disks!",
		[10940] = "Leave this place!",
		[2775] = "You've plundered our treasures too long.  Prepare to meet your watery grave!",
		[10996] = "Be cleansed by blade, filth!",
		[11075] = "Human flesh... must feed!",
		[2949] = "Grrrr... fresh meat!",
		[2950] = "Grrrr... fresh meat!",
		[2951] = "Grrrr... fresh meat!",
		[11443] = "I'll crush you!",
		[3204] = "Играешь на пиратке? Лучше не показывайся мне на глаза!",
		[3275] = "I am slain!  Summon Verog!",
		[3276] = "You will be easy prey, &lt;class&gt;.",
		[3277] = "You will be easy prey, &lt;class&gt;.",
		[3278] = "My talons will shred your puny body, Orc.",
		[3282] = "There's the stolen shredder! Stop it or Lugwizzle will have our hides!",
		[3284] = "Get away from there!",
		[3285] = "Get away from there!",
		[11502] = "BY FIRE BE PURGED!",
		[3395] = "I am summoned!  Intruders, come to my tent and face your death!",
		[3397] = "I am slain!  Summon Verog!",
		[3667] = "Finally, my soul may rest... Oh, dearest Cerellean...",
		[3671] = "None can stand against the Serpent Lords!",
		[11886] = "Well, well. Looks like we got ourselves some competition. Get 'em boys!",
		[3927] = "I can't believe it! You've destroyed my pack... Now face my wrath!",
		[3975] = "Ah - I've been waiting for a real challenge!",
		[3976] = "At your side, milady!",
		[4003] = "I think the sounds came from over here. We'd better check it out.",
		[4004] = "What's going on here? Piznik! I knew we shouldn't have let you stick around!",
		[4062] = "No sign of the final explosives shipment to the west either.  Where are those lollygaggers?",
		[4275] = "Another falls!",
		[4287] = "The light condemns all who harbor evil.  Now you will die!",
		[4299] = "The light condemns all who harbor evil.  Now you will die!",
		[4301] = "The light condemns all who harbor evil.  Now you will die!",
		[4484] = "Assassins from that cult you found... Let's get moving before someone else finds us out here.",
		[4494] = "The light condemns all who harbor evil.  Now you will die!",
		[4540] = "The light condemns all who harbor evil.  Now you will die!",
		[12858] = "Everyone ready?",
		[12918] = "No!  You cannot be stronger than the Foulweald!  No!!",
		[12922] = "Alright I'm going! Stop yelling!",
		[4966] = "Please... please... Miss Proudmore. I didn't mean to...",
		[4969] = "All right, boss. You sure though? Just seems like a waste of good practice.",
		[4971] = "Whoa! This is way more than what I bargained for, you're on your own, Slim!",
		[5234] = "I'll crush you!",
		[5239] = "Me smash! You die!",
		[5240] = "I'll crush you!",
		[5255] = "Grrrr... fresh meat!",
		[5474] = "I'll crush you!",
		[6090] = "Ok, enough!  I give up!",
		[6180] = "Feel the power of the Brotherhood!",
		[6182] = "You won't ruin my lands, you scum!",
		[6221] = "A foul trogg if ever I saw one.  Die!",
		[6238] = "Ready when you are, warrior.",
		[6784] = "Okay, okay... gimmie a minute to rest now. You gone and beat me up good.",
		[7033] = "I'll crush you!",
		[7603] = "A foul trogg if ever I saw one.  Die!,",
	},
}
