deathlog_strings_de = {
	main_font = "Fonts\\FRIZQT__.TTF",
	class_font = "Fonts\\blei00d.TTF",
	death_alert_font = "Fonts\\blei00d.TTF",
	mini_log_font = "Fonts\\blei00d.TTF",
	menu_font = "Fonts\\blei00d.TTF",
	deadliest_creature_container_font = "Fonts\\blei00d.TTF",
	death_alert_default_message = "<name> the <race> <class> has been slain\nby <source> at lvl <level> in <zone>.",
	death_alert_default_fall_message = "<name> the <race> <class> fell to\ndeath at lvl <level> in <zone>.",
	death_alert_default_drown_message = "<name> the <race> <class> drowned\n at lvl <level> in <zone>.",
	death_alert_default_slime_message = "<name> the <race> <class> has died from slime.\n at lvl <level> in <zone>.",
	death_alert_default_lava_message = "<name> the <race> <class> drowned in lava.\n at lvl <level> in <zone>.",
	death_alert_default_fire_message = "<name> the <race> <class> has died from fire.\n at lvl <level> in <zone>.",
	death_alert_default_fatigue_message = "<name> the <race> <class> has died from fatigue.\n at lvl <level> in <zone>.",
	corpse_word = "Leichnam",
	of_word = "von",
	minimap_btn_left_click = "|cFF666666Left Click:|r View log",
	minimap_btn_right_click = "|cFF666666Right Click:|r ",
	class_word = "Klasse",
	killed_by_word = "Getötet von",
	zone_instance_word = "Zone/Instanz",
	date_word = "Datum",
	last_words_word = "Letzte Worte",
	death_word = "Tod",
	guild_word = "Gilde",
	race_word = "Rasse",
	show_heatmap = "Show heatmap",
	class_table = {
		Krieger = "warrior",
		Schurke = "rogue",
		Magier = "mage",
		Priester = "priest",
		Paladin = "paladin",
		Schamane = "shaman",
		Druide = "druid",
		Hexenmeister = "warlock",
		["Jäger"] = "hunter",
	},
	tab_table = {
		{ value = "ClassStatisticsTab", text = "Klassenstatistik" },
		{ value = "CreatureStatisticsTab", text = "Kreaturenstatistik" },
		{ value = "InstanceStatisticsTab", text = "Instanzenstatistik" },
		{ value = "StatisticsTab", text = "Zonenstatistik" },
		{ value = "LogTab", text = "Suche" },
	},
	instance_tbl = {
		{ 33, "SHADOWFANGKEEP", "Burg Shadowfang" },
		{ 36, "DEADMINES", "Die Todesminen" },
		{ 34, "STORMWINDSTOCKADES", "Das Verlies" },
		{ 43, "WAILINGCAVERNS", "Die Höhlen des Wehklagens" },
		{ 47, "RAZORFENKRAUL", "Der Kral von Razorfen" },
		{ 48, "BLACKFATHOMDEEPS", "Blackfathom-Tiefe" },
		{ 90, "GNOMEREGAN", "Gnomeregan" },
		{ 189, "SCARLETMONASTERY", "Das scharlachrote Kloster" },
		{ 70, "ULDAMAN", "Uldaman" },
		{ 109, "SUNKENTEMPLE", "Der Tempel von Atal'Hakkar" },
		{ 129, "RAZORFENDOWNS", "Die Hügel von Razorfen" },
		{ 209, "ZULFARAK", "Zul'Farak" },
		{ 229, "BLACKROCKSPIRE", "Schwarzfelsspitze" },
		{ 230, "BLACKROCKDEPTHS", "Blackrocktiefen" },
		{ 289, "SCHOLOMANCE", "Scholomance" },
		{ 329, "STRATHOLME", "Stratholme" },
		{ 389, "RAGEFIRECHASM", "Ragefire Chasm" },
		{ 349, "MARAUDON", "Maraudon" },
		{ 429, "DIREMAUL", "Düsterbruch" },
		{ 469, "BLACKWINGLAIR", "Blackwing Lair" },
	},
	instance_map = {
		["Burg Shadowfang"] = 33,
		["Das Verlies"] = 34,
		["Die Todesminen"] = 36,
		["Die Höhlen des Wehklagens"] = 43,
		["Der Kral von Razorfen"] = 47,
		["Blackfathom-Tiefe"] = 48,
		["Uldaman"] = 70,
		["Gnomeregan"] = 90,
		["Der Tempel von Atal'Hakkar"] = 109,
		["Die Hügel von Razorfen"] = 129,
		["Das scharlachrote Kloster"] = 189,
		["Zul'Farak"] = 209,
		["Schwarzfelsspitze"] = 229,
		["Blackrocktiefen"] = 230,
		["Scholomance"] = 289,
		["Stratholme"] = 329,
		["Maraudon"] = 349,
		["Ragefire Chasm"] = 389,
		["Düsterbruch"] = 429,
		["Blackwing Lair"] = 469,
	},
	deathlog_zone_tbl = {
		["Azeroth"] = 947,
		["Durotar"] = 1411,
		["Mulgore"] = 1412,
		["The Barrens"] = 1413,
		["Kalimdor"] = 1414,
		["Eastern Kingdoms"] = 1415,
		["Alterac Mountains"] = 1416,
		["Arathi Highlands"] = 1417,
		["Badlands"] = 1418,
		["Blasted Lands"] = 1419,
		["Tirisfal Glades"] = 1420,
		["Silverpine Forest"] = 1421,
		["Western Plaguelands"] = 1422,
		["Eastern Plaguelands"] = 1423,
		["Hillsbrad Foothills"] = 1424,
		["The Hinterlands"] = 1425,
		["Dun Morogh"] = 1426,
		["Searing Gorge"] = 1427,
		["Burning Steppes"] = 1428,
		["Elwynn Forest"] = 1429,
		["Deadwind Pass"] = 1430,
		["Duskwood"] = 1431,
		["Loch Modan"] = 1432,
		["Redridge Mountains"] = 1433,
		["Stranglethorn Vale"] = 1434,
		["Swamp of Sorrows"] = 1435,
		["Westfall"] = 1436,
		["Wetlands"] = 1437,
		["Teldrassil"] = 1438,
		["Darkshore"] = 1439,
		["Ashenvale"] = 1440,
		["Thousand Needles"] = 1441,
		["Stonetalon Mountains"] = 1442,
		["Desolace"] = 1443,
		["Feralas"] = 1444,
		["Dustwallow Marsh"] = 1445,
		["Tanaris"] = 1446,
		["Azshara"] = 1447,
		["Felwood"] = 1448,
		["Un'Goro Crater"] = 1449,
		["Moonglade"] = 1450,
		["Silithus"] = 1451,
		["Winterspring"] = 1452,
	},
}
